### ISSUE TITLE
Различается ник автора на стене и в топиках

### ISSUE THREAD

**Issue by Finitumus** [ImaginariaRU/dear-imaginaria#11]
На стене выводится логин, а в топиках и комментариях собссно никнейм. Непорядок.)
Пример:
https://drive.google.com/file/d/1U4RabviZkd9gIoHirygzKN9-1fQMTwFq/view

**Comment by KarelWintersky** [comment]
Решено.

В сторону: вот кто б знал, что плагин ExpWall не подключает свои шаблоны куда полагается. В итоге сколько угодно можно править настройки в 
`plugins/expwall/templates/skin/default/wall_items_reply.tpl`
```
но править надо файл `templates/skin/synio/actions/ActionProfile/wall_items_reply.tpl`

Нас интересует блок
```
<a href="{$oReplyUser->getUserWebPath()}" class="author">{$oReplyUser->getLogin()}</a>
```
Его можно заменить блоком из шаблона плагина:
```
<a href="{$oReplyUser->getUserWebPath()}" class="author">{if $oReplyUser->getProfileName()}{$oReplyUser->getProfileName()}{else}{$oReplyUser->getLogin()}{/if}</a>
```

**Comment by KarelWintersky** [comment]
Аналогичную правку делаем в `templates/skin/synio/actions/ActionProfile/wall_items.tpl`

В 
```
<p class="info">
   <a href="{$oWallUser->getUserWebPath()}">{$oWallUser->getLogin()}</a> ·
   <time class="date" datetime="{date_format date=$oWall->getDateAdd() format='c'}">{date_format date=$oWall->getDateAdd() hours_back="12" minutes_back="60" now="60" day="day H:i" format="j F Y, H:i"}</time>
</p>
```

Заменяем `{$oWallUser->getLogin()}` на 
```
{if $oWallUser->getProfileName()}{$oWallUser->getProfileName()}{else}{$oWallUser->getLogin()}{/if}
```

**Comment by Finitumus** [comment]
Ура! :)

**Comment by Finitumus** [comment]
С десктопа отображается в комментариях логин юзера, а на стене никнейм. :) 
Мобильную версию я вообще пока не смотрела.)

**Comment by KarelWintersky** [comment]
Гребаный ливстрит. В одном месте сделаешь хорошо - в другом месте ломается. :(

**Comment by KarelWintersky** [comment]
Буду смотреть.

**Comment by Finitumus** [comment]
Меня в похожем движке (Alto CMS, исчадье Ливстрита) спасал только поиск по всему каталогу с кодом, через Searchmonkey. 
И то не уверена, что везде выловила проблему.

**Comment by KarelWintersky** [comment]
Я так и делаю :)

Только у меня в данный момент 4 версии имажинарии: продакшен, слепок недельной давности на моем домене (который надо убить, по хорошему), тестовая на моем домене с обновленным до PHP 7.1 движком и локальная версия (которая не заведена, потому что надо научить жить редмайн, nginx и генту, а у меня лапки).

**Comment by Finitumus** [comment]
Некоторый апдейт: в посте на стене выводится никнейм, а в комментариях к нему таки логины.))

**Comment by KarelWintersky** [comment]
@Finitumus решено? Или нет?

**Comment by Finitumus** [comment]
Можем считать, что решено.) 
Я нашла ещё минимум 1 место, где выводится логин, а не ник, но это не стена (а всплывающий список проголосовавших за топик, если интересно). И в профиле я бы сделала, чтобы крупно и первым выводился ник (который мы теперь везде видим), а надо ли там вообще видеть логин - отдельный вопрос.

**Comment by Finitumus** [comment]
У комментариев к топикам опять выводится логин, а не ник пользователя. Это нормально?

**Comment by KarelWintersky** [comment]
```
/templates/skin/synio/comment.tpl#L36
```
Заменяем 
```
<a href="{$oUser->getUserWebPath()}">{$oUser->getLogin()}</a>
```
на
```
<a href="{$oUser->getUserWebPath()}">{$oUser->getProfileName()}</a>
```
