### ISSUE TITLE
Иконки избранное/поделиться/комментарии/+- не отображается в Vivaldi и Chrome

### ISSUE THREAD

**Issue by DrAfdch** [ImaginariaRU/dear-imaginaria#12]
Chrome Версия 70.0.3538.67 (Официальная сборка), (64 бит)
Vivaldi на Хромиуме, так что корни там же, я полагаю.
В Edge работает.
Win10, если это имеет значение.
https://puu.sh/BNLub/3a9fbf2e46.png

**Comment by KarelWintersky** [comment]
Открыл в вивальди (последнем (?), взятом с сайта) - такого бага у меня нет.
Возможно, Ctrl-F5 поможет.

**Comment by DrAfdch** [comment]
Когда я тестировал в Хроме, там ещё версия 69 была, тоже не работало. 
Вивальди тоже на версии хромиума 69.0.3497.102
Ctrl+F5 естественно пробовал сразу же, не помогло.

**Comment by KarelWintersky** [comment]
Не могу воспроизвести. Мне бы вывод дев-консоли... (я наверное прошу странного?)

**Comment by DrAfdch** [comment]
Почему странного? Очень даже помогло с пониманием, откуда у проблемы растут проблемы, по-моему.
![image](https://user-images.githubusercontent.com/42919427/47257032-3c312400-d491-11e8-9f10-7dbdb66c3d48.png)

**Comment by KarelWintersky** [comment]
только совершенно нет понимания, почему эта хрень происходит. Потому что в файлах **нигде** http не упоминается (не считая комментариев). 

Воспроизвести эту ошибку я не могу. Да, mixed content. Но у нас запросы к http у сайта подменяются на https через плагин - раз, и два - PT Sans никто нигде не хочет.

Может у тебя какие-то аддоны стоят?

**Comment by KarelWintersky** [comment]
исправлено, я надеюсь.

**Comment by DrAfdch** [comment]
Ну я проверить не могу, потому что мобильный вид. В _любом_ из имеющихся у меня браузеров.
![capture](https://user-images.githubusercontent.com/42919427/47265201-d003fe00-d52c-11e8-8959-af06cac7318f.PNG)
В мобильном виде, кстати, иконки отображаются, несмотря на тот же миксед контент. 
![capture1](https://user-images.githubusercontent.com/42919427/47265232-54568100-d52d-11e8-8196-92f69e6a50e9.PNG)
И нет, никаких особых плагинов у меня стоять не должно, да и, судя по комментариям на имочке, не у одного меня такая проблема.

**Comment by KarelWintersky** [comment]
По-видимому на десктопном шаблоне все работает.
