### ISSUE TITLE
[Feature-request] Часть поста сворачивается только в том случае, если сворачиваемая часть больше несворачиваемой

### ISSUE THREAD

**Issue by DrAfdch** [ImaginariaRU/dear-imaginaria#13]
Насколько я понимаю, сейчас ссылка "Читать дальше ->" появляется у любого, даже самого короткого поста.
Насколько я понимаю, она должна появляться только у постов определённой длины (по словам/символам).
Сейчас получается так, что некоторые посты под "катом" имеют одно единственное слово, например, вот. https://puu.sh/BOPWB/b35ee319d1.png https://imaginaria.ru/tech/tehnicheskoe-baghanting-i-bagreporting.html
Кмк, так быть не должно.

Я не знаю, возможно ли пофиксить данную ситуацию, но описанное в заголовке отражает моё видение ситуации, как должно быть.

**Comment by KarelWintersky** [comment]
Будем думать.

**Comment by KarelWintersky** [comment]
Будем думать.

**Comment by KarelWintersky** [comment]
Будем думать.

**Comment by KarelWintersky** [comment]
Исправлено в 72171b95333e308ee8200fa105b831cc9ee22890 

https://github.com/ImaginariaLS/ls_autocut
