### ISSUE TITLE
Подвинуть кнопку "Стена"

### ISSUE THREAD

**Issue by fgfgfgf444g4434522** [ImaginariaRU/dear-imaginaria#15]
![5345345345](https://user-images.githubusercontent.com/44948991/48316365-54591680-e5eb-11e8-8d04-f7820700b8c5.png)
Подвинуть кнопку "Стена" в крайний правый слот, т.к. ей чаще пользуются.

**Comment by KarelWintersky** [comment]
Это не так просто, как выясняется. 
Дело в том, что по умолчанию в меню только 4 пункта:

> Топики, Блоги, Люди и Активность

они задаются в шаблоне `/templates/skin/synio/header_top.tpl`

Пункт "стена" создается плагином ExpWall при ловле хука `{hook run='main_menu_item'}`

вот код вставки (`/plugins/expwall/templates/skin/default/main_menu.tpl`):
```
<li {if $sMenuHeadItemSelect=='wall'}class="active"{/if}>
    <a href="{router page='wall'}">{$aLang.plugin.expwall.title_block}</a>
    <i></i>
</li>
```

Следующие два пункта меню генерируются плагином page.
Они уже берутся из БД, шаблон `/plugins/page/templates/skin/default/main_menu.tpl` таков:
```
{foreach from=$aPagesMain item=oPage}
    <li {if $sAction=='page' and $sEvent==$oPage->getUrl()}class="active"{/if}><a
                href="{router page='page'}{$oPage->getUrlFull()}/">{$oPage->getTitle()}</a><i></i></li>
{/foreach}	
```

**Comment by KarelWintersky** [comment]
К сожалению, плагины активируются по алфавиту и способ изменить порядок отработки плагинов мне неизвестен. 

Можно захардкодить это в шаблоне, но мне это решение не нравится. 

Будем думать.

**Comment by KarelWintersky** [comment]
Решение найдено, осталось его запилить.

**Comment by fgfgfgf444g4434522** [comment]
Спасибо!

**Comment by KarelWintersky** [comment]
Запилено (ценой бессонной ночи)
