### ISSUE TITLE
Ник последнего комментирующего на стене дублируется внизу (Стена)

### ISSUE THREAD

**Issue by fgfgfgf444g4434522** [ImaginariaRU/dear-imaginaria#18]
![image](https://user-images.githubusercontent.com/44948991/48365202-eed05d00-e6b2-11e8-8792-f0e0e0e0d081.png)

**Comment by KarelWintersky** [comment]
Подтверждаю.

**Comment by KarelWintersky** [comment]
Багу нашел, но...

**Comment by KarelWintersky** [comment]
... и исправил.
