### ISSUE TITLE
Выделение комментариев от топикстартера и от админа/модера

### ISSUE THREAD

**Issue by KarelWintersky** [ImaginariaRU/dear-imaginaria#19]
Сейчас комментарий модератора никак не выделяется, рационально выделять его 

```
<div id="comment_content_id_214513" class="comment-content" style="border: 1px solid red;">
```
Проблема: в шаблоне нужно будет сравнивать владельца комментария и список админов.

Комментарий топикстартера сейчас выделяется градиентом на его нике. Люди жалуются, что это неудобно и глаз режет.

Градиент определяется в комбинации этих классов:
```
comment-author comment-topic-author
```
Рационально к DIV 
```
<div id="..." class="comment-content">
```
добавить класс `comment-content-author`, определяющий стиль обводки блока.

**Comment by Finitumus** [comment]
...а, так вот что это была за хрень с градиентом! :)))

**Comment by KarelWintersky** [comment]
И была, и есть.

**Comment by Finitumus** [comment]
Жёлтый градиент в сочетании с серо-синим цветом ника действительно не оч. выглядит. Может, сделать ровный серебристый фон под ником топикстартера, без градиента?

**Comment by KarelWintersky** [comment]
http://livestreet.ru/blog/themes/9346.html
http://livestreet.ru/blog/themes/9385.html

**Comment by KarelWintersky** [comment]
Сделано. 
Цвет администратора `indianred` (`#CD5C5C`)
Цвет топикстартера `#0e90d2`

**Comment by KarelWintersky** [comment]
Переделано
```
.comment.comment-topicstarter .comment-content {
    border-left-color: #0e90d2 !important;
}
.comment.comment-admin .comment-content {
    border-left-color: indianred !important;
}
```
То есть левая граница блока-комментария меняет цвет. 

Через кастомный CSS-файл в `/config/skin/synio.custom.css`
