### ISSUE TITLE
Вложенные комментарии

### ISSUE THREAD

**Issue by KarelWintersky** [ImaginariaRU/dear-imaginaria#5]
Дерево комментариев глубиной больше 5.

**Comment by Finitumus** [comment]
А табличный вариант формата, без веток, не планируется?

**Comment by KarelWintersky** [comment]
> А табличный вариант формата, без веток, не планируется?

@Finitumus , включил сейчас его. Это выглядит уродливо настолько, что лучшенынадо.

**Comment by Finitumus** [comment]
А если нормально сделать? Не прям щас, а в принципе, когда-нибудь. И дать юзерам возможность его включать у себя.
Тот, что сейчас, делали люди, не очень хорошо представляющие себе задачу, и сделали на отвяжись.

**Comment by KarelWintersky** [comment]
Может быть когда-нибудь.

Когда (если) я буду переписывать движок совсем - я учту это пожелание ;-)
