### ISSUE TITLE
Карма

### ISSUE THREAD

**Issue by KarelWintersky** [ImaginariaRU/dear-imaginaria#6]
Есть три варианта:

1. Отключение кармы совсем
2. Отключение минусов
3. Оставить все как есть

**Comment by Finitumus** [comment]
Я за отключение минусов, плюсы и нули пусть остаются, и всё это не обязательно должно быть как-то увязано с возможностями пользователя на фрруме.

**Comment by KarelWintersky** [comment]
Голосование в минус **отключено**.
