### ISSUE TITLE
Обновление движка сайта

### ISSUE THREAD

**Issue by KarelWintersky** [ImaginariaRU/dear-imaginaria#8]
Движок версии 1.0.3. наиболее популярен.

Переход на версию 2.0 не планируется (его разработка не завершена и заброшена полтора года назад).

В сообществе Livestreet обсуждается создание третьей версии движка, но когда он будет - никому неведомо. 

Обновления движка будут касаться решения насущных проблем.

**Comment by DrAfdch** [comment]
http://imka.wintersky.me
Раз уж всё равно писать о том, что в ссылке вместо точки запятая, то можно и ссылку сразу вставить.

**Comment by KarelWintersky** [comment]
Решено, обновлено на совместимость с PHP 7.2
